version: '3.8'
services:
  postgresql:
    image: postgres:15.1
    container_name: prospero_pg
    restart: always
    environment:
      POSTGRES_USER: luffy
      POSTGRES_PASSWORD: toor2023
      POSTGRES_DB: prosperodb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
